version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './public:/var/www/html'
      - './docker/php/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini'
    environment:
      XDEBUG_CONFIG: 'discover_client_host=true client_host=172.17.0.1 log_level=0'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './public:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'




